name: Load Test

on: [push]

jobs:
  loadtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install locust
      - run: |
          locust -f locustfile.py --headless \
            -u 50 -r 5 -t 1m \
            --host=http://<your-service-url> \
            --only-summary \
            --exit-code-on-error 1
